import { LogBox } from "react-native";

export { default as Splash } from "./Common/Splash";
export { default as Login } from "./Common/Login";
export { default as SignUp } from "./Common/SignUp";
export { default as ForgotPassword } from "./Common/ForgotPassword";
export { default as ResetPassword } from "./Common/ResetPassword";
export { default as ShopCategoryWise } from "./User/ShopCategoryWise";
export { default as Recipes } from "./User/Recipes";
export { default as Offers } from "./User/Offers";
export { default as StoreLocator } from "./User/StoreLocator";
export { default as StoreLocatorSideMenu } from "./User/StoreLocatorSideMenu";
export { default as AboutUs } from "./Common/AboutUs";
export { default as UserCart } from "./User/UserCart";
export { default as UserHome } from "./User/UserHome";
export { default as UserProfile } from "./User/UserProfile";
export { default as UserSearch } from "./User/UserSearch";
export { default as MyProfile } from "./User/MyProfile";
export { default as MyOrders } from "./User/MyOrders";
export { default as Address } from "./User/Address";
export { default as AddressListing } from "./User/AddressListing";
export { default as Wishlist } from "./User/Wishlist";
export { default as ProductDetails } from "./User/ProductDetails";
export { default as PaymentOrder } from "./User/PaymentOrder";
export { default as OrderDetails } from "./User/OrderDetails";
export { default as LoyaltyRewards } from "./User/LoyaltyRewards";
export { default as PopularProduct } from "./User/PopularProduct";
export { default as NewProducts } from "./User/NewProducts";
export { default as AllBrowseCategory } from "./User/AllBrowseCategory";
export { default as OrderSuccess } from "./User/OrderSuccess";

LogBox.ignoreAllLogs();
