export const Strings = {
  Login: "Login",
  Email_or_Phone: "Email or Phone",
  Password: "Password",
  Forgot_Password: "Forgot Password ?",
  LoginWithOTP: "Login with OTP",
  Sign_Up: "Sign Up",
  Email: "Email Address",
  Phone: "Phone",
  First_Name: "First Name",
  Last_Name: "Last Name",
  My_Profile: "My Profile",
  My_Order: "My Orders",
  Logout: "Logout",
  Select_store: "Select Store",
  Enter_pincode: "Enter Pincode",
  My_Cart: "My Cart",
  Best_value: "Best Value Offers",
  BrowseText: "Browse By Category",
  Popular_product: "Popular Products",
};
export default Strings;
