export const Strings = {
  Login: "Login",
  Email_or_Phone: "Email or Phone",
  Password: "Password",
  Forgot_Password: "Forgot Password ?",
  LoginWithOTP: "Login with OTP",
  Sign_Up: "Sign Up",
  Email: "Email Address",
  Phone: "Phone",
  First_Name: "First Name",
  Last_Name: "Last Name",
  My_Profile: "My Profile",
  My_Order: "My Orders",
  Logout: "Logout",
  Logout_Msg: "Are you sure you want to logout?",
  Select_store: "Select Store",
  Enter_pincode: "Enter Pincode",
  My_Cart: "My Cart",
  Best_value: "Best Value Offers",
  BrowseText: "Browse By Category",
  Popular_product: "Popular Products",
  Cancel: "Cancel",
  Ok: "OK",
  Internet_Error: "No internet connection, please try again later.",
  Server_Error: "Server Error, please try again later.",
  Network_Error: "Network Error",
  No_Internet_Error: "No Internet Connection",
  Retry: "Retry",
  Forgot_password: "Forgot Password",
  Send: "Send",
  Yes: "Yes",
  No: "No",
  //Error
  error_email: "Please enter your email",
  error_valid_email: "Please enter your valid email",
  error_password: "Please enter your password",
  error_firstname: "Please enter first Name",
  error_lastname: "Please enter last Name",
  error_phone: "Please enter your phone",
  error_valid_phone_number: "Please enter valid Phone Number of 10 digits",
  error_valid_password:
    // "Password must be 8 characters long with at least one uppercase letter, one special character and one number",
    "Password must be at least 8 characters long",
};
export default Strings;
