export const Strings = {
  Login: "Login",
  Email_or_Phone: "Email or Phone",
  Password: "Password",
  OldPassword: "Old Password",
  NewPassword: "New Password",
  ConfrimPassword: "Confirm Password",
  Forgot_Password: "Forgot Password ?",
  LoginWithOTP: "Login with OTP",
  ResendOTP: "Resend OTP",
  Sign_Up: "Sign Up",
  Email: "Email Address",
  Phone: "Phone",
  OTP: "OTP",
  First_Name: "First Name",
  Last_Name: "Last Name",
  My_Profile: "My Profile",
  Wishlist: "Wishlist",
  My_Order: "My Orders",
  ChangePassoword: "Change Passoword",
  Logout: "Logout",
  Logout_Msg: "Are you sure you want to logout?",
  Select_store: "Select Store",
  Enter_pincode: "Enter Pincode",
  My_Cart: "My Cart",
  Best_value: "Best Value Offers",
  BrowseText: "Browse By Category",
  Popular_product: "Popular Products",
  Cancel: "Cancel",
  Ok: "OK",
  Submit: "Submit",
  Internet_Error: "No internet connection, please try again later.",
  Server_Error: "Server Error, please try again later.",
  Network_Error: "Network Error",
  No_Internet_Error: "No Internet Connection",
  Retry: "Retry",
  Forgot_password: "Forgot Password",
  ResetPassword: "Reset Password",
  Send: "Send",
  Yes: "Yes",
  No: "No",
  NewProduct: "New Products",
  Popular_category: "Popular Categories",
  Why_Fairshop: "Why Fairshop",
  today_cook: "What do you want to\ncook today ?",
  Select_Store: "Select Store",
  Add: "Add",
  CheckOut: "Checkout",
  Subtotal: "Subtotal",
  TaxableAmount: "Taxable Amount",
  CGST: "CGST",
  SGST: "SGST",
  IGST: "IGST",
  TotalAmount: "Total Amount",
  Addresses: "Addresses",
  Contact_No: "Contact No.",
  Date_of_Birth: "Date of Birth",
  Gender: "Gender",
  Marital_Status: "Marital Status",
  Profile_Picture: "Profile Picture",
  Upload: "Upload",
  Address_Type: "Address Type",
  Address_Label: "Address Label",
  Receiver_name: "Receiver's Full Name",
  Address_Line_1: "Address Line 1",
  Address_Line_2: "Address Line 2",
  Landmark: "Landmark",
  City: "City",
  State: "State",
  Pincode: "Pincode",
  Add_Address: "Add Address",

  //Error
  error_email_phone: "Please enter your email or phone",
  error_email: "Please enter your email",
  error_valid_email: "Please enter your valid email",
  error_password: "Please enter your password",
  error_firstname: "Please enter first Name",
  error_lastname: "Please enter last Name",
  error_phone: "Please enter your phone",
  error_valid_phone_number: "Please enter valid Phone Number of 10 digits",
  error_valid_password:
    // "Password must be 8 characters long with at least one uppercase letter, one special character and one number",
    "Password must be at least 8 characters long",
  error_password_match: "Password and Confirm Password do not match!",
  error_old_password: "Please enter old password",
  error_new_password: "Please enter new password",
  error_confirm_password: "Please enter confirm password",
  error_otp: "Please enter OTP",
  error_addressType: "Please enter Address Type",
  error_addressLabel: "Please enter Address Label",
  error_receiver_name: "Please enter Receiver's Full Name",
  error_contact_no: "Please enter Contact No.",
  error_addressline1: "Please enter Address Line 1",
  error_addressline2: "Please enter Address Line 2",
  error_city: "Please enter City",
  error_State: "Please enter State",
  error_pincode: "Please enter Pincode",
  error_DOB: "Please enter Date of Birth",
  error_gender: "Please enter Gender",

  Menu: "Menu",
  ShopbyCategories: "Shop by Categories",
  Recipes: "Recipes",
  Offers: "Offers",
  AboutUs: "About Us",
  StoreLocator: "Store Locator",
  AddToCart: "Add to Cart",
  Description: "Description",
  Share: "Share",
  Tweet: "Tweet",
  Email: "Email",
  Date_of_Anniversary: "Date of Anniversary",
  Update: "Update",
  PlaceOrder: "Place Order",
  OrderNotes: "Order Notes",
  ShippingAddress: "Shipping Address",
  BillingAddress: "Billing Address",
  PaymentMethod: "Payment Method",
  Razorpay: "Razorpay",
  COD: "Cash on Delivery",
  ProceedPayment: "Proceed to Payment",
  No_data_found: "No data found",

  No_Stores_Suggestion:
    "No store serves to your location\nOur Services are available for areas under these pincodes:",

  error_Address: "Please select shipping address",
  error_BillingAddress: "Please select billing address",
  error_paymentMode: "Please select payment mode",
};
export default Strings;
