export const Route = {
  Splash: "Splash",
  Login: "Login",
  SignUp: "SignUp",
  ForgotPassword: "ForgotPassword",
  ResetPassword: "ResetPassword",
  AboutUs: "AboutUs",
  Offers: "Offers",
  Recipes: "Recipes",
  ShopCategoryWise: "ShopCategoryWise",
  StoreLocator: "StoreLocator",
  DrawerApp: "DrawerApp",
  UserCart: "UserCart",
  UserHome: "UserHome",
  UserProfile: "UserProfile",
  UserSearch: "UserSearch",
  BottomTabApp: "BottomTabApp",
  MyProfile: "MyProfile",
  MyOrders: "MyOrders",
  Address: "Address",
  AddressListing: "AddressListing",
  ProductDetails: "ProductDetails",
  Wishlist: "Wishlist",
  PaymentOrder: "PaymentOrder",
  OrderDetails: "OrderDetails",
  LoyaltyRewards: "LoyaltyRewards",
};
