export const Route = {
  Splash: 'Splash',
  Login: 'Login',
  SignUp: 'SignUp',
  AboutUs: 'AboutUs',
  Offers: 'Offers',
  Recipes: 'Recipes',
  ShopCategoryWise: 'ShopCategoryWise',
  StoreLocator: 'StoreLocator',
  DrawerApp: 'DrawerApp',
  UserCart: 'UserCart',
  UserHome: 'UserHome',
  UserProfile: 'UserProfile',
  UserSearch: 'UserSearch',
  BottomTabApp: 'BottomTabApp',
};
